package com.sterlite.dccmappfordealersterlite.model.dto.usersignup;

import java.io.Serializable;

public  class UserSignUpWsResponseDTO  implements Serializable 
{

 	/** Default serialVersionUID value. */
 
 	private static final long serialVersionUID = 1L;

	/** Response code<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.responseCode</code> property defined at extension <code>vfoccaddon</code>. */

    private String responseCode;

	/** Response Message<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.responseMessage</code> property defined at extension <code>vfoccaddon</code>. */

    private String responseMessage;

	/** CustomerID unique ID generated by DCCM for Lead
			<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.customerId</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String customerId;

	/** Open/Flexi field for future use<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.field1</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String field1;

	/** Open/Flexi field for future use<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.field2</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String field2;

	/** Open/Flexi field for future use<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.field3</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String field3;

	/** Open/Flexi field for future use<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.field4</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String field4;

	/** Open/Flexi field for future use<br/><br/><i>Generated property</i> for <code>UserSignUpWsResponseDTO.field5</code> property defined at extension <code>vfoccaddon</code>. */
		
	private String field5;
	
	public UserSignUpWsResponseDTO()
	{
		// default constructor
	}
	
		
	
	public void setResponseCode(final String responseCode)
	{
		this.responseCode = responseCode;
	}

		
	
	public String getResponseCode() 
	{
		return responseCode;
	}
	
		
	
	public void setResponseMessage(final String responseMessage)
	{
		this.responseMessage = responseMessage;
	}

		
	
	public String getResponseMessage() 
	{
		return responseMessage;
	}
	
		
	
	public void setCustomerId(final String customerId)
	{
		this.customerId = customerId;
	}

		
	
	public String getCustomerId() 
	{
		return customerId;
	}
	
		
	
	public void setField1(final String field1)
	{
		this.field1 = field1;
	}

		
	
	public String getField1() 
	{
		return field1;
	}
	
		
	
	public void setField2(final String field2)
	{
		this.field2 = field2;
	}

		
	
	public String getField2() 
	{
		return field2;
	}
	
		
	
	public void setField3(final String field3)
	{
		this.field3 = field3;
	}

		
	
	public String getField3() 
	{
		return field3;
	}
	
		
	
	public void setField4(final String field4)
	{
		this.field4 = field4;
	}

		
	
	public String getField4() 
	{
		return field4;
	}
	
		
	
	public void setField5(final String field5)
	{
		this.field5 = field5;
	}

		
	
	public String getField5() 
	{
		return field5;
	}

	@Override
	public String toString() {
		return "UserSignUpWsResponseDTO{" +
				"responseCode='" + responseCode + '\'' +
				", responseMessage='" + responseMessage + '\'' +
				", customerId='" + customerId + '\'' +
				", field1='" + field1 + '\'' +
				", field2='" + field2 + '\'' +
				", field3='" + field3 + '\'' +
				", field4='" + field4 + '\'' +
				", field5='" + field5 + '\'' +
				'}';
	}
}