package com.elitecore.elitesmp.utility;

public interface EliteSMPUtilConstants {
    /*
     *
     * Webin URL generator parameters
     */
    String ELITESMP_URL = "elitesmpurl";
    String ELITESMP_URL_WSGETPACKAGE = "wsGetPackages";
    String ELITESMP_URL_WSGETPAYMENTGATEWAY = "wsGetPaymentGateway";
    String ELITESMP_URL_WSREGISTERACCOUNT = "wsRegisterAccount";
    String ELITESMP_URL_WSLOGIN = "wsLogin";
    String ELITESMP_URL_WSLOGOUT = "wsSubscriberLogout";
    String ELITESMP_URL_WSRECHARGEACCOUNT = "wsRechargeAccount";
    String ELITESMP_URL_WSVOUCHERVERIFICATION = "wsVoucherVerification";
    String ELITESMP_URL_WSGetBrandData = "wsGetBrandData";
    String ELITESMP_URL_WSGETPARTNERDATA = "wsGetPartnerData";
    String ELITESMP_URL_WSGETSUBSCRIBERDATA = "wsGetSubscriberData";
    String ELITESMP_URL_WSSENDOTP = "wsSendOTP";
    String ELITESMP_URL_WSVERIFYOTP = "wsVerifyOTP";
    String ELITESMP_URL_WSDBSCAN = "wsDBScan";
    String ELITESMP_URL_WSRENEWACCOUNT = "wsRenewAccount";
    String ELITESMP_URL_WSPASSWORDVERIFICATION = "wsPasswordVerification";
    String ELITESMP_URL_WSINITIATEPAYMENTREQUEST = "wsInitiatePaymentRequest";


    String ELITESMP_URL_WSPGLOGIN = "wsPGLogin";
    String ELITESMP_URL_WSPGLOGOUT = "wsPGLogout";
    String ELITESMP_URL_WSFORGOTPASSWORD = "wsForgotPassword";
    String ELITESMP_URL_WSSENDNOTIFICATION = "wsSendNotification";
    String ELITESMP_URL_WSNETVERTEXGETBALANCE = "wsNetVertexGetBalance";
    String ELITESMP_URL_WSUPDATESESSION = "wsUpdateSession";
    String ELITESMP_URL_WSVERIFYSESSION = "wsVerifySession";
    String MOBILE_NO = "MobileNo";
    String MOBILE_NO_SMALL = "mobileNo";
    String AMOUNT = "amount";
    String LANGUAGE = "language";
    String MASTERCARDREDIRECT = "VALUE_MASTERCARDREDIRECT";
    String KEY_ERROR_EXPLANATION = "KEY_ERROR_EXPLANATION";

    /*
        Constants for SMP key, which later on need to migrated in property file elitesmp.property
     */
    String FRAMEDIPADDRESS = "FramedIPAddress";
    String SERVICETYPE = "ServiceType";
    String CONNECTIONTYPE = "ConnectionType";
    String SERVICETYPE_SMALL = "serviceType";
    String LOCATION = "Location";
    String LOCATION_SMALL = "location";
    String LOCATION_ALL = "ALL";
    String OPERATION = "Operation";
    String OPERATION_SMALL = "operation";
    String SUBENCRYPTIONTYPE = "Sub.EncryptionType";
    String RESPONSETIME = "ResponseTime";
    String PASSWORD = "Password";
    String NEWPASSWORD = "NewPassword";
    String SUBSESSIONCOUNT = "Sub.SessionCount";
    String SUBPASSWORD = "Sub.Password";
    String SUBLOGINSERVICEPOLICY = "Sub.LoginServicePolicy";
    String ACCESSDEVICEIP = "AccessDeviceIP";
    String SUBBALANCE = "Sub.Balance";
    String SUBSUBSCRIBERID = "Sub.SubscriberId";
    String SUBACCOUNTNUMBER = "Sub.AccountNumber";
    String SUBSOURCEPORT = "Sub.SourcePort";
    String SUBVOLUMEBASEDUSEDQUOTA = "Sub.VolumeBasedUsedQuota";
    String SUBTIMEBASEDUNUSEDQUOTA = "Sub.TimeBasedUnusedQuota";
    String SUBFAILUREATTEMPT = "Sub.FailureAttempt";
    String SUBUSERNAME = "Sub.UserName";
    String FIRSTNAME = "FirstName";
    String EMAIL = "Email";
    String PHONE = "Phone";
    String PGWIPURL = "PG.WIPURL";
    String SUBPARAM2 = "Sub.Param2";
    String REPLYMESSAGE = "ReplyMessage";
//    String SUBPARAM3 = "Sub.Param3";


    String PACKAGEBASE = "PackageBase";
    String SUBPASSWORDVALIDITY = "Sub.PasswordValidity";
    String SUBVOLUMEBASEDTOTALQUOTA = "Sub.VolumeBasedTotalQuota";
    String SUBTIMEBASEDTOTALQUOTA = "Sub.TimeBasedTotalQuota";
    String SUBTIMEBASEDUSEDQUOTA = "Sub.TimeBasedUsedQuota";
    String SUBVOLUMEBASEDUNUSEDQUOTA = "Sub.VolumeBasedUnusedQuota";
    String VOUCHERCODE = "voucherCode";
    String VOUCHERCODE_CAP = "VoucherCode";
    String OPERATIONMODE = "OperationMode";
    String VOUCHERPIN = "VoucherPin";
    String SUBVOUCHERCODE = "Sub.VoucherCode";
    String SUBSUBSCRIBERIDENTITY = "Sub.SubscriberIdentity";
    String PACKAGEID = "Package.ID";
    String SUBPHONE = "Sub.Phone";
    String SUB_LOCATION = "Sub.Location";
    String OTP = "OTP";
    String REGISTRATION = "REGISTRATION";
    String RENEWAL = "RENEWAL";
    String ADV_LOCATION = "Avd_Location";


    /*
    These constants should be declared into ELITE SMP property file defined as application specific
     */
    String KEY_SUBCUI = "KEYSUBCUI";
    String KEY_CHANNEL = "KEY_CHANNEL";
    String KEY_PACKAGEID = "KEY_PACKAGEID";
    String KEY_IPADDRESS = "KEY_IPADDRESS";
    String KEY_PHONE = "KEY_PHONE";
    String KEY_NAME = "KEY_NAME";
    String KEY_OPERATION = "KEY_OPERATION";
    String KEY_BASESEARCH = "KEY_BASESEARCH";
    String KEY_QUERYDATA = "KEY_QUERYDATA";
    String KEY_RECORDFETCHCOUNT = "KEY_RECORDFETCHCOUNT";
    String KEY_PARAM1 = "KEY_PARAM1";
    String KEY_PARAM2 = "KEY_PARAM2";
    String KEY_PARAM3 = "KEY_PARAM3";
    String KEY_PARAM4 = "KEY_PARAM4";
    String KEY_PARAM5 = "KEY_PARAM5";
    String KEY_PARAM6 = "KEY_PARAM6";
    String KEY_PARAM7 = "KEY_PARAM7";
    String KEY_PARAM8 = "KEY_PARAM8";
    String KEY_PARAM10 = "KEY_PARAM10";
    String KEY_CPARAMDU = "KEY_CPARAMDU";
    String KEY_CPARAMDUP = "KEY_CPARAMDUP";
    String KEY_CPARAM_SOURCE = "KEY_CPARAM_SOURCE";

    String KEY_PPARAMDU = "KEY_PPARAMDU";
    String KEY_PPARAMDUP = "KEY_PPARAMDUP";
    String KEY_PPARAM_SOURCE = "KEY_PPARAM_SOURCE";
    String RESULTCODE = "ResultCode";

    String KEY_MSISDN = "KEY_MSISDN";
    String KEY_SERVICETYPE = "KEY_SERVICETYPE";
    String KEY_FIRSTNAME = "KEY_FIRSTNAME";
    String KEY_SUBUSERNAME = "KEY_SUBUSERNAME";
    String KEY_SUBFIRSTNAME = "KEY_SUBFIRSTNAME";
    String KEY_SUBEMAIL = "KEY_SUBEMAIL";
    String KEY_COUNT = "KEY_COUNT";
    String KEY_MOBILE = "KEY_MOBILE";
    String KEY_UPDATEDDATE = "KEY_UPDATEDDATE";
    String KEY_EXPIRYDATE = "KEY_EXPIRYDATE";
    String KEY_FLAG = "KEY_FLAG";
    String KEY_PACKAGE_TYPE_PREMIUM = "KEY_PACKAGE_TYPE_PREMIUM";
    String VALUE_PACKAGE_PREMIUM = "VALUE_PACKAGE_PREMIUM";
    String VALUE_WSDB_NAME = "VALUE_WSDB_NAME";
    String VALUE_OPERATION_REGISTRATION = "VALUE_OPERATION_REGISTRATION";
    String VALUE_OPERATION_READ = "VALUE_OPERATION_READ";
    String VALUE_OPERATION_UPDATE = "VALUE_OPERATION_UPDATE";
    String VALUE_OPERATION_DELETE = "VALUE_OPERATION_DELETE";
    String VALUE_SERVICETYPE_WALKIN = "VALUE_SERVICETYPE_WALKIN";
    String VALUE_SERVICESTYPE_FREE = "VALUE_SERVICESTYPE_FREE";
    String VALUE_SERVICETYPE_COMPLEMENTARY1 = "VALUE_SERVICETYPE_COMPLEMENTARY1";
    String VALUE_SERVICETYPE_COMPLIMENTARY = "VALUE_SERVICETYPE_COMPLIMENTARY";
    String VALUE_SERVICESTYPE_CONTINUE_COMPLIMENTARY = "VALUE_SERVICESTYPE_CONTINUE_COMPLIMENTARY";
    String VALUE_SERVICETYPE_GENERIC = "VALUE_SERVICETYPE_GENERIC";
    String VALUE_DBSCAN_SERVICENAME_VALIDATEOTP = "VALUE_DBSCAN_SERVICENAME_VALIDATEOTP";
    String VALUE_DBSCAN_SERVICENAME_MANAGE_MAC_DBS = "VALUE_DBSCAN_SERVICENAME_MANAGE_MAC_DBS";
    String VALUE_DBSCAN_SERVICENAME_MANAGESPEED = "VALUE_DBSCAN_SERVICENAME_MANAGESPEED";
    String VALUE_DBSCAN_SERVICENAME_BLACKLIST_MSISDN = "BLACKLIST_MSISDN";
    String VALUE_DBSCAN_SERVICENAME_SURVEY = "VALUE_DBSCAN_SERVICENAME_SURVEY";
    String VALUE_DBSCAN_SERVICENAME_AAALOOKUP = "VALUE_DBSCAN_SERVICENAME_AAALOOKUP";
    String VALUE_OPERATION_CREATE = "VALUE_OPERATION_CREATE";
    String VALUE_OPERATION_DBSCAN = "VALUE_OPERATION_DBSCAN";
    String VALUE_OTP_SEND = "VALUE_OTP_SEND";
    String VALUE_OTP_VARIFY = "VALUE_OTP_VARIFY";
    String WEBSERVICES_RESPONSE_SUCCESS = "WEBSERVICES_RESPONSE_SUCCESS";
    String WEBSERVICES_RESPONSE_RECORDCOUNT = "WEBSERVICES_RESPONSE_RECORDCOUNT";
    String WEBSERVICES_RESPONSE_RESPONSEDATA = "WEBSERVICES_RESPONSE_RESPONSEDATA";
    String WEBSERVICES_RESPONSE_OTP_SENT_SUCCESS = "WEBSERVICES_RESPONSE_OTP_SENT_SUCCESS";
    String WEBSERVICES_RESULTCODE = "WEBSERVICES_RESULTCODE";
    String WEBSERVICES_RESPONSE_REPLYMESSAGE = "WEBSERVICES_RESPONSE_REPLYMESSAGE";
    String WEBSERVICES_REPLYMESSAGE_VALUE = "WEBSERVICES_REPLYMESSAGE_VALUE";
    String WEBSERVICES_RESPONSE_COUNT = "WEBSERVICES_RESPONSE_COUNT";
    String WEBSERVICES_SUBSCRIBER_EXPIRYDATE = "WEBSERVICES_SUBSCRIBER_EXPIRYDATE";
    String WEBSERVICES_SUBSCRIBER_RESULTCODE = "WEBSERVICES_SUBSCRIBER_RESULTCODE";
    String MESSAGE_DATA = "MESSAGE_DATA";
    String MESSAGE_VERIFICATION_CODE = "MESSAGE_VERIFICATION_CODE";
    String MESSAGE_DATA_ACTION = "MESSAGE_DATA_ACTION";
    String KEY_MOBILENUMBER = "KEY_MOBILENUMBER";
    String KEY_USERIDENTITY = "KEY_USERIDENTITY";
    String KEY_PASSWORD = "KEY_PASSWORD";
    String KEY_USERNAME = "KEY_USERNAME";
    String KEY_VOUCHERCODE = "KEY_VOUCHERCODE";
    String KEY_VOUCHERCODECAP = "KEY_VOUCHERCODECAP";
    String KEY_EMAIL = "KEY_EMAIL";
    String KEY_BRAND = "brand";
    String KEY_BRAND_notify = "Brand";
    String KEY_SUBBRAND = "KEY_SUBBRAND";
    String KEY_PARTNER = "KEY_PARTNER";
    String KEY_FRAMEDIPADDRESS = "KEY_FRAMEDIPADDRESS";
    String KEY_SOURCE = "source";
    String VALUE_SOURCE = "app";
    String KEY_USERIDENTITY_VALUE = "userIdentity";
    String KEY_USERNAME_VALUE = "UserName";
    String KEY_UAMIP = "KEY_UAMIP";
    String KEY_LOCATION = "KEY_LOCATION";
    String KEY_TYPE = "KEY_TYPE";
    String KEY_OTP = "KEY_OTP";
    String KEY_SUB_PASSWORD = "KEY_SUB_PASSWORD";
    String VALUE_OTP_OPERATION_PREMIUM = "VALUE_OTP_OPERATION_PREMIUM";
    String KEY_WEBINCWS = "KEY_WEBINCWS";
    String KEY_PASSWORD_CAP = "KEY_PASSWORD_CAP";
    String KEY_OPERATION_CAP = "KEY_OPERATION_CAP";
    String VALUE_SERVICE_TYPE = "VALUE_SERVICE_TYPE";
    String KEY_PG_SELECTEDPAYGW = "KEY_PG_SELECTEDPAYGW";
    String KEY_PACKAGE_PRICE = "Package.Price";
    String KEY_PACKAGE_PRICE_DESC = "DESC";
    String KEY_PACKAGE_VALIDITY = "KEY_PACKAGE_VALIDITY";
    String KEY_PACKAGE_ID = "KEY_PACKAGE_ID";
    String VALUE_PACKAGE_ID = "VALUE_PACKAGE_ID";
    String KEY_CREDITCARDNUMBER = "KEY_CREDITCARDNUMBER";
    String KEY_CVVNUMBER = "KEY_CVVNUMBER";
    String KEY_SSID = "KEY_SSID";
    String KEY_REGISTRATIONMETHOD = "KEY_REGISTRATIONMETHOD";
    String KEY_APPARAMETER = "KEY_APPARAMETER";
    String KEY_PG_AUTHSTATU = "KEY_PG.AUTHSTATU";
    String KEY_USERAGENT_TYPE = "KEY_USERAGENT_TYPE";
    String VALUE_USERAGENT_TYPE = "VALUE_USERAGENT_TYPE";
    String VALUE_PREMIUM_LOGIN_TYPE = "VALUE_PREMIUM_LOGIN_TYPE";
    String VALUE_PREMIUM_LOGIN_SSID = "VALUE_PREMIUM_LOGIN_SSID";
    String KEY_SUBSCRIBERIDENTITY = "KEY_SUBSCRIBERIDENTITY";
    String VALUE_PREMIUM_REGISTRATION_METHOD = "VALUE_PREMIUM_REGISTRATION_METHOD";

    String KEY_NVLOC = "KEY_NVLOC";

    String KEY_PAYMENT_TRANSACTION_ID = "KEY_PAYMENT_TRANSACTION_ID";
    String KEY_PAYMENT_GATEWAY_TRANSACTION_ID = "KEY_PAYMENT_GATEWAY_TRANSACTION_ID";
    String KEY_SELECTEDPAYMENT_GATEWAY = "KEY_SELECTEDPAYMENT_GATEWAY";
    String KEY_PAYMENT_AUTH_STATUS = "KEY_PAYMENT_AUTH_STATUS";
    String CREDITCARD_SUCCESS_URL = "CREDITCARD_SUCCESS_URL";
    String KEY_MAC = "KEY_MAC";
    String KEY_IP = "KEY_IP";
    String KEY_LANDINGPAGEMSGARB = "KEY_LANDINGPAGEMSGARB";
    String KEY_LANDINGPAGEMSGENG = "KEY_LANDINGPAGEMSGENG";

    String WEBSERVICES_TRANSACTIONSTATUS = "WEBSERVICES_TRANSACTIONSTATUS";
    String WEBSERVICES_TRANSACTIONSTATUS_SUCCESS = "WEBSERVICES_TRANSACTIONSTATUS_SUCCESS";
    String WEBSERVICES_PG_RESPONSEPARAMSTR = "WEBSERVICES_PG_RESPONSEPARAMSTR";
    String BRANDNAME = "BRANDNAME";
    String PAYMENT_METHOD_WOW_CARD = "PAYMENT_METHOD_WOW_CARD";
    String PAYMENT_METHOD_CREDIT_CARD = "PAYMENT_METHOD_CREDIT_CARD";
    String CURRENCY_TYPE_KEY = "CURRENCY_TYPE_KEY";
    String CURRENCY_TYPE_VALUE = "CURRENCY_TYPE_VALUE";
    String REGISTRATION_METHOD = "REGISTRATION_METHOD";
    String PARTNERNAME = "PARTNERNAME";
    String PGSELECTEDPAYGW = "PG.SelectedPayGw";
    String AUTHSTATUS = "AUTHSTATUS";
    String CARDIDENTIFYNUMBER = "CARDIDENTIFYNUMBER";
    String LOGIN_TYPE_RESUME = "LOGIN_TYPE_RESUME";
    String LOGIN_TYPE_RESUME_PIN_VERIFICATION = "LOGIN_TYPE_RESUME_PIN_VERIFICATION";
    String VALUE_BRAND = "VALUE_BRAND";
    String VALUE_LOGIN_PARAM6 = "VALUE_LOGIN_PARAM6";
    String VALUE_LOGIN_PARAM5 = "VALUE_LOGIN_PARAM5";
    String VALUE_WEBINCWS = "VALUE_WEBINCWS";
    String VALUE_WIP_URL = "VALUE_WIP_URL";
    String PAYMENT_SUCCESS_URL = "PAYMENT_SUCCESS_URL";

    String CREDITCARD_500 = "500";
    String CREDITCARD_469 = "469";
    String CREDITCARD_SUB_PARAM_10 = "CREDITCARD_SUB_PARAM_10";
    String INAP64 = "INAP64";
    String INAP65 = "INAP65";
    String INAP66 = "INAP66";
    String INAP67 = "INAP67";
    String INAP68 = "INAP68";
    String UNKNOWN_PAYMENT_CODE = "UNKNOWN_PAYMENT_CODE";
    String CREDITCARD_00 = "00";
    String CREDITCARD_01 = "01";
    String CREDITCARD_05 = "05";
    String CREDITCARD_06 = "06";
    String CREDITCARD_09 = "09";
    String CREDITCARD_14 = "14";
    String CREDITCARD_54 = "54";
    String CREDITCARD_56 = "56";
    String CREDITCARD_68 = "68";
    String CREDITCARD_94 = "94";
    String REDIRECT_USER = "REDIRECT_USER";
    String KEY_OFFLOAD_FLAG = "KEY_OFFLOAD_FLAG";
    String KEY_REDIRECTIONURL = "KEY_REDIRECTIONURL";

    String KEY_TIMEBASEDUNUSEDQUOTA = "KEY_TIMEBASEDUNUSEDQUOTA";
    String KEY_VOLUMEBASEDUNUSEDQUOTA = "KEY_VOLUMEBASEDUNUSEDQUOTA";
    String KEY_EXPIRYDATELOGIN = "KEY_EXPIRYDATELOGIN";

    String VALUE_PGFREE_USERNAME = "VALUE_PGFREE_USERNAME";
    String VALUE_PGFREE_PASSWORD = "VALUE_PGFREE_PASSWORD";
    String VALUE_PGFREE_SERVICETYPE = "VALUE_PGFREE_SERVICETYPE";

    String KEY_SUBPHONE = "KEY_SUBPHONE";

    String VALUE_MYACCOUNT_LOGIN_URL = "VALUE_MYACCOUNT_LOGIN_URL";
    String VALUE_MYACCOUNT_LOGINSUBMIT_URL = "VALUE_MYACCOUNT_LOGINSUBMIT_URL";
    String LOCATION_PACKAGE = "LOCATION_PACKAGE";
    String KEY_SUB_LOCATION = "KEY_SUB_LOCATION";
    String KEY_SERVICE_TYPE = "KEY_SERVICE_TYPE";
    String KEY_SURVEYTYPEID = "KEY_SURVEYTYPEID";
    String VALUE_DBSCAN_SERVICENAME_GET_LOGGED_IN_USER = "VALUE_DBSCAN_SERVICENAME_GET_LOGGED_IN_USER";
    String VALUE_DBSCAN_SERVICENAME_GET_USED_FREE_MONTHLY_QUOTA = "VALUE_DBSCAN_SERVICENAME_GET_USED_FREE_MONTHLY_QUOTA";
    String VALUE_DBSCAN_SERVICENAME_GET_USERLIST_BY_NUMBER = "VALUE_DBSCAN_SERVICENAME_GET_USERLIST_BY_NUMBER";
    String VALUE_DBSCAN_SERVICENAME_FETCH_SUB_ID = "VALUE_DBSCAN_SERVICENAME_FETCH_SUB_ID";
    String VALUE_DBSCAN_SERVICENAME_MAC_UPDATE_DELETE = "VALUE_DBSCAN_SERVICENAME_MAC_UPDATE_DELETE";


    String KEY_SUBACCOUNTNUMBER = "KEY_SUBACCOUNTNUMBER";

    String KEY_DBSCAN_FIRSTNAME = "KEY_DBSCAN_FIRSTNAME";
    String KEY_DBSCAN_USED_VOL = "KEY_DBSCAN_USED_VOL";
    String KEY_DBSCAN_UNUSED_VOL = "KEY_DBSCAN_UNUSED_VOL";
    String KEY_DBSCAN_UNUSED_TIME = "KEY_DBSCAN_UNUSED_TIME";
    String KEY_DBSCAN_PASSWORD = "KEY_DBSCAN_PASSWORD";
    String KEY_DBSCAN_ExpiryDate = "KEY_DBSCAN_ExpiryDate";
    String KEY_DBSCAN_SubVolumeBasedUsedQuota = "KEY_DBSCAN_SubVolumeBasedUsedQuota";
    String KEY_DBSCAN_VOLUME_USED_QUOTA = "KEY_DBSCAN_VOLUME_USED_QUOTA";

    String KEY_QUOTAINMB = "KEY_QUOTAINMB";

    String VALUE_DUMMY_VOUCHER = "VALUE_DUMMY_VOUCHER";


    String KEY_ACCOUNT_IDNETITY = "KEY_ACCOUNT_IDNETITY";
    String KEY_ACCOUNT_USER = "KEY_ACCOUNT_USER";
    String KEY_ACCOUNT_PASS = "KEY_ACCOUNT_PASS";
    String KEY_ACCOUNT_SERVICETYPE = "KEY_ACCOUNT_SERVICETYPE";
    String KEY_ACCOUNT_LOCATION = "KEY_ACCOUNT_LOCATION";

    String VALUE_ACCOUNT_IDNETITY = "VALUE_ACCOUNT_IDNETITY";
    String VALUE_ACCOUNT_LOCATION = "VALUE_ACCOUNT_LOCATION";

    String KEY_CREATED_DATE = "KEY_CREATED_DATE";
    String KEY_EXPIRY_DATE = "KEY_EXPIRY_DATE";
    String KEY_USER_SUBSCRIBERIDENTITY = "KEY_USER_SUBSCRIBERIDENTITY";


    String KEY_SUBTIMEBASEDTOTALQUOTA = "KEY_SUBTIMEBASEDTOTALQUOTA";
    String KEY_SUBTIMEBASEDUSEDQUOTA = "KEY_SUBTIMEBASEDUSEDQUOTA";
    String KEY_SUBVOLUMEBASEDTOTALQUOTA = "KEY_SUBVOLUMEBASEDTOTALQUOTA";
    String KEY_SUBVOLUMEBASEDUSEDQUOTA = "KEY_SUBVOLUMEBASEDUSEDQUOTA";

    String KEY_PARAM1_TYPE = "KEY_PARAM1_TYPE";
    String KEY_PARAM5_TYPE = "KEY_PARAM5_TYPE";
    String VALUE_PARAM5_TYPE = "VALUE_PARAM5_TYPE";

    //    String KEY_REPORT_PROBLEM_EMAIL = "KEY_REPORT_PROBLEM_EMAIL";
//    String KEY_REPORT_PROBLEM_PASSWORD = "KEY_REPORT_PROBLEM_PASSWORD";
    String KEY_DUMMY_USERNAME = "KEY_DUMMY_USERNAME";
    String KEY_DUMMY_PASSWORD = "KEY_DUMMY_PASSWORD";
    String KEY_DUMMY_SERVICETYPE = "KEY_DUMMY_SERVICETYPE";
    String KEY_ONLINE_PAYMENT_MAXCOUNT = "KEY_ONLINE_PAYMENT_MAXCOUNT";
    String KEY_SEND_OTP_MAXCOUNT = "KEY_SEND_OTP_MAXCOUNT";
    String KEY_RESET_OTP_TIME_INMINUTE = "KEY_RESET_OTP_TIME_INMINUTE";
    String KEY_FREE_SERVICETYPE = "KEY_FREE_SERVICETYPE";
    String KEY_PAID_SERVICETYPE = "KEY_PAID_SERVICETYPE";
    String KEY_NEOX_CUSTOMER_URL = "KEY_NEOX_CUSTOMER_URL";

    String WEBSERVICES_RESPONSE_RESPONSEDATA1 = "WEBSERVICES_RESPONSE_RESPONSEDATA1";

    String KEY_CLIENT_MAC = "client_mac";

    String KEY_MESSAGE_OTP_BLOCK = "KEY_MESSAGE_OTP_BLOCK";
    String KEY_MESSAGE_MOBILENO_REGISTER = "KEY_MESSAGE_MOBILENO_REGISTER";
    String KEY_MESSAGE_DEVICE_RAGISTER = "KEY_MESSAGE_DEVICE_RAGISTER";
    String KEY_MESSAGE_FREE_DAILY_QUOTAOVER = "KEY_MESSAGE_FREE_DAILY_QUOTAOVER";
    String KEY_MESSAGE_FREE_MONTHLY_QUOTAOVER = "KEY_MESSAGE_FREE_MONTHLY_QUOTAOVER";
    String KEY_MESSAGE_PAYMENT_GATEWAY_BLOCK = "KEY_MESSAGE_PAYMENT_GATEWAY_BLOCK";
    String KEY_MESSAGE_CONCURRENCY_CHECK = "KEY_MESSAGE_CONCURRENCY_CHECK";
    String KEY_MESSAGE_PAID_QUOTAOVER = "KEY_MESSAGE_PAID_QUOTAOVER";

    String KEY_CONTACTUS_MOBILENO = "KEY_CONTACTUS_MOBILENO";
    String KEY_NEOX_SECRETKEY = "KEY_NEOX_SECRETKEY";
    String KEY_NEOX_LIST_ID = "KEY_NEOX_LIST_ID";
    String KEY_NEOX_DUBLICATE_CHECKLIST = "KEY_NEOX_DUBLICATE_CHECKLIST";
    String KEY_NEOX_IS_DUBLICATE_PHONENO = "KEY_NEOX_IS_DUBLICATE_PHONENO";
    String KEY_IS_INTERNATIONAL_NO_SUPPORT = "KEY_IS_INTERNATIONAL_NO_SUPPORT";

    String KEY_PLAN_STATUS = "KEY_PLAN_STATUS";
    String KEY_PLAN_OPERATION = "KEY_PLAN_OPERATION";
    String KEY_CHECK_PLAN_PRIZE = "KEY_CHECK_PLAN_PRIZE";

    String VALUE_NEOX_CALLBACK_URL = "VALUE_NEOX_CALLBACK_URL";

    String KEY_NEOX_OPEN_TIME = "KEY_NEOX_OPEN_TIME";
    String KEY_NEOX_CLOSE_TIME = "KEY_NEOX_CLOSE_TIME";
    String KEY_NEOX_SUCCESS_MESSAGE = "KEY_NEOX_SUCCESS_MESSAGE";
    String KEY_NEOX_FAILURE_MESSAGE = "KEY_NEOX_FAILURE_MESSAGE";
    String KEY_NEOX_NETWORK_ERROR_MESSAGE = "KEY_NEOX_NETWORK_ERROR_MESSAGE";


    String KEY_CALLBACK_SECRET_KEY = "KEY_CALLBACK_SECRET_KEY";
    String KEY_CALLBACK_DATA = "KEY_CALLBACK_DATA";
    String KEY_CALLBACK_DUBLICATE_CHECKLIST = "KEY_CALLBACK_DUBLICATE_CHECKLIST";
    String KEY_CALLBACK_IS_DUBLICATE_PHONENO = "KEY_CALLBACK_IS_DUBLICATE_PHONENO";

    String KEY_VERIFYOTP_MOBILENUMBER = "KEY_VERIFYOTP_MOBILENUMBER";
    String KEY_VERIFYOTP_OTP = "KEY_VERIFYOTP_OTP";
    String KEY_USERNAME_SMALL = "userName";
    String SUBPARAM4 = "Sub.Param4";
    String NV_LOC_CODE = "NV_LOC_CODE";
    String LOGINFLAG = "LoginFlag";
    String ACTIONNAME = "actionName";
    String SUBPARAM3 = "Sub.Param3";
    String SUBPARAM10 = "Sub.Param10";
    String ISUNLIMITED = "IsUnlimited";
    String SUCCESS = "SUCCESS";
    String LOGIN = "LOGIN";
    String LIMITED = "LIMITED";
    String UNLIMITED = "UNLIMITED";
    String DISCONNECT = "DISCONNECT";
    String LOGOUT = "LOGOUT";
    String NETWORKACTION = "NetworkAction";
    String DISCONNECT_SMALL = "disconnect";
    String SWITCHLOGOUT = "switchLogout";
    String SWITCHLOGIN = "switchLogin";

    String KEY_WIP_URL = "KEY_WIP_URL";
    String KEY_VOLUME_TOTAL_QUOTA = "KEY_VOLUME_TOTAL_QUOTA";
    String KEY_DAILYTIMEBASEDUSEDQUOTA = "KEY_DAILYTIMEBASEDUSEDQUOTA";
    String KEY_DAILYVOLUMEBASEDUSEDQUOTA = "KEY_DAILYVOLUMEBASEDUSEDQUOTA";

    // MasterCard Constant in SMP
    String MC_SESSIONID = "MC.SessionId";
    String MC_SUCCESSINDICATOR = "MC.successIndicator";
    String MC_ORDERID = "MC.OrderId";
    String PG_TRANSACTIONID = "PG.TransactionId";
    String MASTERCARDPAYMENT = "MasterCardPaymentGroovy";
    String CURRENCY = "currency";
    String PAYMENT_METHOD_MASTER_CARD = "PAYMENT_METHOD_MASTER_CARD";

    String VALUE_OTP_OPERATION = "VALUE_OTP_OPERATION";
    String SUBSCRIBERPACKAGE = "Sub.SubscriberPackage";
    String TYPE = "Type";
    String KEY_SUB_PARAM1 = "KEY_SUB_PARAM1";
    String PAYMENTGATEWAY = "PAYMENTGATEWAY";
    String RESPONSEDATA = "ResponseData";

    String GENERIC_SERVICE_TYPE = "Generic";
    String KEY_MOBILENUMBER_VALUE = "mobileNumber";
    String OTP_SMALL = "otp";
    String KEY_PASSWORD_VALUE = "password";
    String KEY_PASSWORD_CAP_VALUE = "Password";
    String KEY_IP_VALUE = "uamip";
    String SERVICETYPE_COMPLEMENTARY = "Complementary";
    String USERAGENTTYPE = "UserAgent.Type";
    String KEY_WEBSERVICES_SUBSCRIBER_EXPIRYDATE = "Sub.ExpiryDate";
    String VALUE_USERAGENTTYPE = "AndroidApp";
    String BRAND_VALUE = "eclair";
    String KEY_PARAM1_VALUE = "Param1";
    String KEY_PARAM2_VALUE = "Param2";
    String KEY_PARAM3_VALUE = "Param3";
    String KEY_PARAM4_VALUE = "Param4";
    String KEY_PARAM5_VALUE = "Param5";
    String KEY_PARAM6_VALUE = "Param6";
    String KEY_PARAM7_VALUE = "Param7";
    String KEY_PARAM8_VALUE = "Param8";
    String KEY_PARAM10_VALUE = "Param10";
    String KEY_PARAM11_VALUE = "Param11";
    String NO = "No";
    String YES = "Yes";
    String KEY_WEBINCWS_VALUE = "webincws";
    String VALUE_WEBINCWS_VALUE = "true";
    String SERVICETYPE_CONTINUECOMPLEMENTARY = "ContinueComplementary";
    String PARTNER = "Partner";
    String REGISTRATIONMETHOD ="RegistrationMethod";
    String TOPUP = "TopUp";
    String SSID = "SSID";
    String CREDITCARD = "CreditCard";
    String CREDITCARDNUMBER = "CreditCardNumber";

}
