package com.sterlite.dccmappfordealersterlite.model.dto.user;

import java.io.Serializable;

/**
 * Created by elitecore on 12/9/18.
 */

public class UserResponseWsDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    /** Response code<br/><br/><i>Generated property</i> for <code>UserResponseWsDTO.responseCode</code> property defined at extension <code>vfoccaddon</code>. */

    private String responseCode;

    /** Response Message<br/><br/><i>Generated property</i> for <code>UserResponseWsDTO.responseMessage</code> property defined at extension <code>vfoccaddon</code>. */

    private String responseMessage;

    /** CustomerID unique ID generated by DCCM for Lead
     <br/><br/><i>Generated property</i> for <code>UserResponseWsDTO.user</code> property defined at extension <code>vfoccaddon</code>. */

    private UserWsDTO user;

    public String getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    public String getResponseMessage() {
        return responseMessage;
    }

    public void setResponseMessage(String responseMessage) {
        this.responseMessage = responseMessage;
    }

    public UserWsDTO getUser() {
        return user;
    }

    public void setUser(UserWsDTO user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "UserResponseWsDTO{" +
                "responseCode='" + responseCode + '\'' +
                ", responseMessage='" + responseMessage + '\'' +
                ", user=" + user +
                '}';
    }
}
